/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowScoresWorkRouteImport } from './routes/how-scores-work'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EscapeBoardRouteImport } from './routes/escape-board'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminDealsNewRouteImport } from './routes/admin.deals.new'
import { Route as AdminDealsDealIdEditRouteImport } from './routes/admin.deals.$dealId.edit'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowScoresWorkRoute = HowScoresWorkRouteImport.update({
  id: '/how-scores-work',
  path: '/how-scores-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EscapeBoardRoute = EscapeBoardRouteImport.update({
  id: '/escape-board',
  path: '/escape-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsNewRoute = AdminDealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsDealIdEditRoute = AdminDealsDealIdEditRouteImport.update({
  id: '/deals/$dealId/edit',
  path: '/deals/$dealId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/escape-board': typeof EscapeBoardRoute
  '/explore': typeof ExploreRouteWithChildren
  '/how-scores-work': typeof HowScoresWorkRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/watchlist': typeof WatchlistRoute
  '/welcome': typeof WelcomeRoute
  '/admin/import': typeof AdminImportRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/admin/deals/new': typeof AdminDealsNewRoute
  '/admin/deals/$dealId/edit': typeof AdminDealsDealIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/escape-board': typeof EscapeBoardRoute
  '/explore': typeof ExploreRouteWithChildren
  '/how-scores-work': typeof HowScoresWorkRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/watchlist': typeof WatchlistRoute
  '/welcome': typeof WelcomeRoute
  '/admin/import': typeof AdminImportRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/admin/deals/new': typeof AdminDealsNewRoute
  '/admin/deals/$dealId/edit': typeof AdminDealsDealIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/escape-board': typeof EscapeBoardRoute
  '/explore': typeof ExploreRouteWithChildren
  '/how-scores-work': typeof HowScoresWorkRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/watchlist': typeof WatchlistRoute
  '/welcome': typeof WelcomeRoute
  '/admin/import': typeof AdminImportRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/admin/deals/new': typeof AdminDealsNewRoute
  '/admin/deals/$dealId/edit': typeof AdminDealsDealIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate-disclosure'
    | '/auth'
    | '/contact'
    | '/escape-board'
    | '/explore'
    | '/how-scores-work'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/terms'
    | '/trips'
    | '/watchlist'
    | '/welcome'
    | '/admin/import'
    | '/deals/$dealId'
    | '/explore/$slug'
    | '/admin/deals/new'
    | '/admin/deals/$dealId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate-disclosure'
    | '/auth'
    | '/contact'
    | '/escape-board'
    | '/explore'
    | '/how-scores-work'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/terms'
    | '/trips'
    | '/watchlist'
    | '/welcome'
    | '/admin/import'
    | '/deals/$dealId'
    | '/explore/$slug'
    | '/admin/deals/new'
    | '/admin/deals/$dealId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate-disclosure'
    | '/auth'
    | '/contact'
    | '/escape-board'
    | '/explore'
    | '/how-scores-work'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/terms'
    | '/trips'
    | '/watchlist'
    | '/welcome'
    | '/admin/import'
    | '/deals/$dealId'
    | '/explore/$slug'
    | '/admin/deals/new'
    | '/admin/deals/$dealId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EscapeBoardRoute: typeof EscapeBoardRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  HowScoresWorkRoute: typeof HowScoresWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TripsRoute: typeof TripsRoute
  WatchlistRoute: typeof WatchlistRoute
  WelcomeRoute: typeof WelcomeRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-scores-work': {
      id: '/how-scores-work'
      path: '/how-scores-work'
      fullPath: '/how-scores-work'
      preLoaderRoute: typeof HowScoresWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escape-board': {
      id: '/escape-board'
      path: '/escape-board'
      fullPath: '/escape-board'
      preLoaderRoute: typeof EscapeBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals/new': {
      id: '/admin/deals/new'
      path: '/deals/new'
      fullPath: '/admin/deals/new'
      preLoaderRoute: typeof AdminDealsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals/$dealId/edit': {
      id: '/admin/deals/$dealId/edit'
      path: '/deals/$dealId/edit'
      fullPath: '/admin/deals/$dealId/edit'
      preLoaderRoute: typeof AdminDealsDealIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminDealsNewRoute: typeof AdminDealsNewRoute
  AdminDealsDealIdEditRoute: typeof AdminDealsDealIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminDealsNewRoute: AdminDealsNewRoute,
  AdminDealsDealIdEditRoute: AdminDealsDealIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EscapeBoardRoute: EscapeBoardRoute,
  ExploreRoute: ExploreRouteWithChildren,
  HowScoresWorkRoute: HowScoresWorkRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TripsRoute: TripsRoute,
  WatchlistRoute: WatchlistRoute,
  WelcomeRoute: WelcomeRoute,
  DealsDealIdRoute: DealsDealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
